arch:
  - aarch64
description: Backup client
image: registry.gitlab.com/abilbaotm/hassio-urbackup
init: false
name: Urbackup
slug: urbackup
url: https://gitlab.com/abilbaotm/hassio-urbackup
version: 0.1.0
schema:
  URBACKUP_SERVER_NAME: str
  URBACKUP_CLIENT_NAME: str
  URBACKUP_CLIENT_AUTHKEY: str
options:
  URBACKUP_SERVER_NAME: urbackup-server.local
  URBACKUP_CLIENT_NAME: homeassistant.local
  URBACKUP_CLIENT_AUTHKEY: 1234567890ABC
map:
  - backup
