arch:
  - aarch64
description: Backup client
image: registry.gitlab.com/abilbaotm/hassio-urbackup
init: false
name: Urbackup
slug: urbackup
url: https://gitlab.com/abilbaotm/hassio-urbackup
version: latest
schema:
  URBACKUP_SERVER_NAME: str
options:
  URBACKUP_SERVER_NAME: urbackup-server.local
