arch:
  - aarch64
description: It is a self-hosted monitoring tool like "Uptime Robot"
image: registry.gitlab.com/abilbaotm/addon-uptime-kuma
init: false
name: Uptime Kuma
ports:
  3001/tcp: 3001
ports_description:
  3001/tcp: Web interface
slug: uptime-kuma
url: https://github.com/abilbaotm/addon-uptime-kuma
version: 0.5.2
webui: http://[HOST]:[PORT:3001]
