arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
codenotary: codenotary@frenck.dev
description: It is a self-hosted monitoring tool like "Uptime Robot"
image: registry.gitlab.com/abilbaotm/addon-uptime-kuma:latest
init: false
name: Uptime Kuma
ports:
  3001/tcp: 3001
ports_description:
  3001/tcp: Web interface
slug: uptime-kuma
url: https://github.com/abilbaotm/addon-uptime-kuma
version: latest
webui: http://[HOST]:[PORT:3001]
